ansible_user: azureuser
ansible_ssh_private_key_file: ~/.ssh/roboshop-azure
node_version: "18.x"
redis_conf_file: /etc/redis/redis.conf

mongo_host: mongodb.roboshop.internal
mysql_host: mysql.roboshop.internal
redis_host: redis.roboshop.internal
rabbitmq_host: rabbitmq.roboshop.internal