# 📦 Install RabbitMQ

- name: Install RabbitMQ
  apt:
    name: rabbitmq-server
    state: present
    update_cache: yes

# ▶️ Enable and start service

- name: Enable and start RabbitMQ
  service:
    name: "{{ rabbitmq_service_name }}"
    state: started
    enabled: yes

# 🐍 Install Python dependency for Ansible RabbitMQ module

- name: Install RabbitMQ Python dependency
  apt:
    name: python3-pika
    state: present

# 👤 Create application user

- name: Create RabbitMQ user
  community.rabbitmq.rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_password }}"
    permissions:
      - vhost: /
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
    state: present