- name: Install MySQL on Ubuntu
  when: ansible_os_family == "Debian"
  block:

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

- name: Install MySQL on RHEL
  when: ansible_os_family == "RedHat"
  block:

    - name: Install MySQL server
      dnf:
        name: mysql-server
        state: present

# 🔥 Start MySQL

- name: Start MySQL service
  service:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: yes
  
- name: Install PyMySQL dependency
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes

# 🔐 Set root password (idempotent)

- name: Set MySQL root password
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: true
    priv: "*.*:ALL,GRANT"
    state: present


# 🌐 Allow remote connections

- name: Allow remote connections
  replace:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify: restart mysql
  when: ansible_os_family == "Debian"