- name: Installing MySQL Server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Starting and enabling MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set MySQL root password
  shell: |
    sudo mysql <<EOF
    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';
    FLUSH PRIVILEGES;
    EOF
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Allow remote connections
  replace:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify: restart mysql