- name: Install MongoDB client
  apt:
    name: mongodb-clients
    state: present
    update_cache: yes

# 🔥 Check DB existence

- name: Check if catalogue DB exists
  command: >
    mongo --host {{ mongo_host }} --quiet
    --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: mongo_check
  changed_when: false

# 🔥 Load schema only once

- name: Load catalogue schema
  shell: >
    mongo --host {{ mongo_host }} < /app/db/master-data.js
  when: mongo_check.stdout | int < 0