pipeline {

    agent any

    environment {
        ANSIBLE_HOST_KEY_CHECKING = "False"
    }

    stages {

        stage('Verify Ansible') {
            steps {
                sh 'ansible --version'
            }
        }

        stage('Deploy RoboShop') {
            steps {
                sh '''
                    chmod +x jenkins/deploy.sh
                    ./jenkins/deploy.sh
                '''
            }
        }
    }

    post {

        success {
            echo 'RoboShop deployment successful!'
        }

        failure {
            echo 'Deployment failed!'
        }
    }
}